### ISSUE TITLE
[FEATURE SUGGESTION] - Bidirectional Highway syntax

### ISSUE THREAD

**Issue by alessandroperilli** [Trung0246/ComfyUI-0246#10]
I finally started testing the Highway and Junction node in a serious way. (I also plan to test the other batch of new ones, which look seriously powerful).

Hence, I remembered one of the reasons why I had to postpone the adoption of either in the AP Workflow: #2. 
Without the capability to reverse direction of in and out pins, my workflow would become an unsustainable mess. 

That said, while testing the Highway node, I found myself in the situation of attempting to replicate a stack of reroute nodes:

<img width="178" alt="Screenshot 2023-11-26 at 21 18 02" src="https://github.com/Trung0246/ComfyUI-0246/assets/9775949/e1a0042b-e9f3-4280-8437-1a14e8ca1f46">

Writing down every label in both directions is a minor annoyance, but it gave me the idea for a tweak of the syntax (if possible).

Right now we write a query like `>pinA, <pinA`. 
Could we write a query like `<>pinA` to shortcut the creation of two in and out pins with identical labels*? 

Just a thought.

**UPDATE**
You have implemented the layout direction! I just didn't notice until now. But, just like for rgthree, when the layout is reversed, the pin labels disappear. Is that a technical limitation of ComfyUI? If so, this whole Issue is mostly pointless.

**Comment by Trung0246** [comment]
Hm not sure since I used rgthree function to actually do the heavy works of flipping layout. Since I don't have control over that you could try to ask over rgthree repo.

**Comment by Trung0246** [comment]
Probably gonna close this too since the issue over rgthree got closed and it looks like inherent limitation unfortunately.

https://github.com/rgthree/rgthree-comfy/issues/58
