### ISSUE TITLE
Error only when piping through Merge node.

### ISSUE THREAD

**Issue by Pojo267** [Trung0246/ComfyUI-0246#13]
The Highway node receives an error when piping in from a Merge. I haven't tested it on values other than String.

Output "StringName" is not defined or is not of type "STRING". Expected "str".

If I pipe directly from another Highway, this error does not occur. Only when piping in from a Merge node.

**Comment by Trung0246** [comment]
Can you share the buggy workflow?

**Comment by Trung0246** [comment]
@Pojo267 just a reminder
