### ISSUE TITLE
Is it possible to pass the output of junction to a reroute node (Ideally from rgthree)?

### ISSUE THREAD

**Issue by stephantual** [Trung0246/ComfyUI-0246#17]
Trying to make my layout looks nice . Imagine a standard junction node with model, latent, and a few ints etc. Let's imagine i want to output just the clip, but i want to route it first. Can I do that? 

Right now i'm using collapsed junctions or 'cast reroutes' as reroutes but it doesn't feel 'right', becaues one carries the whole context and the other is, correct me if i'm wrong, purely intended for casting.

Thank you. Amazing nodes 💯

**Comment by Trung0246** [comment]
Hm I think Rgthree already have the relay node. Maybe you could use that for meantime.

**Comment by stephantual** [comment]
Thank you and Happy New Year! Makes sense - The reason I was asking was to 'display' what was going where within a group as part of super large worflows , in order to make sense of the inputs which aren't standards (say, arbitrary ints or floats). Thank you for making this so flexible! I appreciate your help.
