### ISSUE TITLE
Cannot connect anything to Highway nodes.

### ISSUE THREAD

**Issue by Pojo267** [Trung0246/ComfyUI-0246#18]
I have completely wiped and freshly installed ComfyUI with nothing but the custom node Manger and 0246 nodes installed. I've tested in both Chrome and Edge while on incognito to ensure no extensions caused any issues. No matter what I do, if I try to connect any node to a highway node, the path and the highway node get stuck to my cursor and I am unable to get rid of it until I delete the highway node.

![8a9e566e5fc23eef0098c1d8211f6cb1](https://github.com/Trung0246/ComfyUI-0246/assets/74991641/d09640cb-5bd4-454b-a45a-5e95d0b575cb)

**Comment by Trung0246** [comment]
Woops my bad when shifting code around. It should be fixed now.
