### ISSUE TITLE
[REQUEST] Documentation/Tips on using the Looping Functions

### ISSUE THREAD

**Issue by Gerkinfeltser** [Trung0246/ComfyUI-0246#19]
Hello Trung0246,

I'm reaching out to express my appreciation for your work on comfyui! I'm currently delving into the looping functionality which seems unique and super powerful, and find myself needing a bit more guidance to fully utilize them.

Could you provide additional documentation or examples that clarify the intended use-cases, practical implementation, and any best practices for these looping functions? I've looked through your example workflow in the repository but still can't quite wrap my head around it honestly.

Your insights would be invaluable to me and others in the community looking to deepen our understanding of these features! Thank you for your time and for the invaluable resource you've created. Your expertise and assistance are greatly appreciated!

**Comment by Trung0246** [comment]
I'm planning on rework the `Hold` soon so stay tuned :)

**Comment by Trung0246** [comment]
![workflow_loop_demo](https://github.com/Trung0246/ComfyUI-0246/assets/11626920/9faf97ef-97cb-4eed-b7ae-83bd8fae3562)

The latest patch I have reworked the `Hold` node. This workflow example should be the starting point for messing around with `Loop` :)

**Comment by Gerkinfeltser** [comment]
Hello again, I actually updated the extension & ran the workflow above again. I'm still getting an error but it seems different. You also asked for the node number. I'm attaching an image of that as well! Both attached images are from the top chain of the  workflow. I notice there is a "key: 44" (first image) as well as a node with #44. Not sure if that means anything (second image).

```
got prompt
ERROR:root:Failed to validate prompt for output 37:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: data
ERROR:root:* 0246.Beautify 37:
ERROR:root:  - Required input is missing: data
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 41:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: data
ERROR:root:* 0246.Beautify 41:
ERROR:root:  - Required input is missing: data
ERROR:root:Output will be ignored
Prompt executor has been patched by Job Iterator!
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**input_data_all))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 933, in execute
    lib0246.hijack(execution, "map_node_over_list", map_node_over_list_param_handle)
        ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '44'

Prompt executed in 0.01 seconds
```

![image](https://github.com/Trung0246/ComfyUI-0246/assets/1477787/f1d98c7d-be10-4f41-afce-0febacefff09)
![image](https://github.com/Trung0246/ComfyUI-0246/assets/1477787/9f599eb0-c081-4693-8d8e-336055b40736)

**Comment by Trung0246** [comment]
Can you download the latest patch and run the workflow again?

**Comment by Gerkinfeltser** [comment]
Starting out, I'll just update my comfy (& the 0246 extension) & see if that fixes it. I'll get back to you. 😄

**Comment by Gerkinfeltser** [comment]
Yep, it must have been comfy being out of date! Seems to be working fine after doing an "Update All" via manager. Sorry for the false alarm!
