### ISSUE TITLE
[BUG?] STRING widgets stick on screen

### ISSUE THREAD

**Issue by mortael** [Trung0246/ComfyUI-0246#21]
Hey,

I have the following when I have ComfyUI-0246 installed.
STRING widgets that should be out of screen, stay sometimes sticked on the canvas.
Screenshot:
![image](https://github.com/Trung0246/ComfyUI-0246/assets/418733/387a1b9e-ccd0-47bb-9b54-60e0662e9338)

It's most noticeable with 'Follow Execution' on (from Comfyui-custom-scripts), but without it also happens.
I tried a new clean install of ComfyUI, with only ComfyUI-0246 installed, and using the 'Default' nodes to generate the purple glass image.
I copied those nodes 2 or 3 times, each placed out of screen. I then run the prompt, and go from the running node to one of the others out of screen. And then the STRING widget from the Clip Text Node sticks on screen.
It goes away when I go back to it.

It happens random, so not each time every STRING widget, sometimes only the Positive one, the other time both.
The same happens a lot with Note nodes.

What could this be?

**Comment by Trung0246** [comment]
Hm weird. I tried to literally copy-pasting z-index management verbatim from the comfyui dom widget implementation. It looks like I missed something. Checking now.

**Comment by Trung0246** [comment]
Pushed temp fix that should hopefully works for now. Will keep this issue open.

**Comment by mortael** [comment]
Thanks, with the temp fix I don't have those sticky widgets anymore 👍
