### ISSUE TITLE
Multiline widget textboxes stick on screen

### ISSUE THREAD

**Issue by rgthree** [Trung0246/ComfyUI-0246#22]
(Originally filed here, but looks like it's this custom node: https://github.com/comfyanonymous/ComfyUI/issues/2568 )

Steps:

1. Install ComfyUI-0246.
1. Open default workflow.
2. Go ahead and a note too, though the clip text encode text boxes will show it too.
3. Add a node offscreen, and note its node id.
4. Move the canvas back to your main workflow, with the text areas.
5. call `app.canvas.centerOnNode(app.graph.getNodeById(12))` where 12 is the node id of the node offscreen.
6. Note that the canvas has moved to be centered on that node, but the three textboxes remain floating on top.

![Screenshot 2024-01-16 170110](https://github.com/comfyanonymous/ComfyUI/assets/476360/f1a94dff-8dff-4465-81cd-55081f591eb2)

**Comment by Trung0246** [comment]
Trying emergency fix this right now. Will have to deep dive on how comfyui managing the element display and zooming being work. I copy-pasted verbatim the addDOMWidget and this somehow break things. Weird.

Reference: https://github.com/Trung0246/ComfyUI-0246/issues/21

**Comment by Trung0246** [comment]
Also @rgthree , do you have any ideas on relevant issues in the past that relates to `addDOMWidget`? The current goal is I'm trying to implement an alternative dynamic widget size mechanism like in ComfyUI.

**Comment by sarashinai** [comment]
> Trying emergency fix this right now. Will have to deep dive on how comfyui managing the element display and zooming being work. I copy-pasted verbatim the addDOMWidget and this somehow break things. Weird.
> 
> Reference: [#21](https://github.com/Trung0246/ComfyUI-0246/issues/21)
> 
> Close as dupe.

What was your emergency fix? I'm not sure if I'm having the same issue our not but it does seem to be related to one of my own nodes.

![Image](https://github.com/user-attachments/assets/72876486-0355-4163-bda6-1d8c29641e9b)

**Comment by Trung0246** [comment]
@sarashinai honestly I kinda forgot what I did before, but you can take a look here for reference: https://github.com/Trung0246/ComfyUI-0246/blob/d09cb3fe8266e4731316955a99c28dd721ee26cd/web/js/widgets.js#L1461

**Comment by sarashinai** [comment]
> [@sarashinai](https://github.com/sarashinai) honestly I kinda forgot what I did before, but you can take a look here for reference:
> 
> [ComfyUI-0246/web/js/widgets.js](https://github.com/Trung0246/ComfyUI-0246/blob/d09cb3fe8266e4731316955a99c28dd721ee26cd/web/js/widgets.js#L1461)
> 
> Line 1461 in [d09cb3f](/Trung0246/ComfyUI-0246/commit/d09cb3fe8266e4731316955a99c28dd721ee26cd)
>  draw: function (ctx, node, widget_width, y, widget_height) {

Thanks, I tracked it down to https://github.com/Trung0246/ComfyUI-0246. I had to do a fresh install as I couldn't get rid of all the code it had injected.
