### ISSUE TITLE
Got “\nodes.py", line 1405, in execute if Hold.HOLD_DB[_key_id]["mode"] == "save":”

### ISSUE THREAD

**Issue by ultimatech-cn** [Trung0246/ComfyUI-0246#23]
When executing hold node, got following error message: 
 File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 1405, in execute
    if Hold.HOLD_DB[_key_id]["mode"] == "save":

what is valid setting for mode?

**Comment by Gerkinfeltser** [comment]
Actually, I'm getting the same issue & I was using the embedded workflow in the example image you posted for the demo. Here's the full error:

`got prompt
ERROR:root:Failed to validate prompt for output 37:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: data
ERROR:root:* 0246.Beautify 37:
ERROR:root:  - Required input is missing: data
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 41:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: data
ERROR:root:* 0246.Beautify 41:
ERROR:root:  - Required input is missing: data
ERROR:root:Output will be ignored
Prompt executor has been patched by Job Iterator!
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**input_data_all))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 933, in execute
    Hold.HOLD_DB[_key_id[0]]["data"] = []
    ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '44'

Prompt executed in 0.06 seconds`

**Comment by Trung0246** [comment]
Hm looks like I changed something again. Will take further look.

**Comment by Trung0246** [comment]
I think the latest version did changed something. Update to latest version and probably try again.

**Comment by Gerkinfeltser** [comment]
I'll move back to my original request issue with further issues/updates on this if that's ok! As you mentioned sounds like my issue may not be directly related to @ultimatech-cn. Sorry for the added noise here!

**Comment by Trung0246** [comment]
Pinging @ultimatech-cn

**Comment by ultimatech-cn** [comment]
Thanks!  I am trying other method for loop method. I will try this solution later.

**Comment by Trung0246** [comment]
Gonna close this since it feels like there's no longer issues. Feels free to reopen.
