### ISSUE TITLE
What does it mean "documentation can be shown directly in the UI if rgthree is installed"

### ISSUE THREAD

**Issue by stephantual** [Trung0246/ComfyUI-0246#28]
I'm very curious :) 

In the gh repo it reads 'MORE DOCUMENTATION (can be shown directly in the UI if rgthree is installed).
I have rgthree, how do i access it?

Thank you!

**Comment by Trung0246** [comment]
Oh it was an experiment. The help popup would be shown if right click on the nodes. It was supposed to have same behavior like rgthree since I borrowed functions from.
