### ISSUE TITLE
[FEATURE REQUEST] Support for Reroute (native and 3rd parties) nodes in Junction

### ISSUE THREAD

**Issue by alessandroperilli** [Trung0246/ComfyUI-0246#3]
The Junction node would be extremely useful if I could connect Reroute nodes to it. Especially rghtree Reroute nodes.

For example, in the following screenshots, I would like to replicate that stack of reversed rgthree Reroute nodes with a single Junction node, but I cannot:

<img width="388" alt="Screenshot 2023-11-07 at 13 18 08" src="https://github.com/Trung0246/ComfyUI-0246/assets/9775949/a79fa138-5ec3-4a15-8ff6-3d86e2e3329d">

This really is the main use case that triggered my wish list for this node.

**Comment by Trung0246** [comment]
Hm since reroute nodes are virtual nodes it may behave differently. Not sure how to deal with this but I'll looks into it.

Btw did you connect the reroute node to the static pin like _junc_in or the dynamic pins? It maybe due to type check problem since reroute node did not have type.

**Comment by alessandroperilli** [comment]
I connected the reroute node to a dynamic node, because I want to recreate exactly the stack you see in the screenshot (they are all reroute nodes), but with Junction.

I understand a possible objection: "Why don't you simply place Junction right before the source node you want to transport?" 
The answer to a similar objection is that very often the source nodes are spread apart or in awkward positions and a reroute node is often necessary.

**Comment by Trung0246** [comment]
I guess you means "dynamic pins" not "dynamic nodes" but yeah that the underlying problem of reroute node have unknown type.

**Comment by Trung0246** [comment]
I have change some code. Can you test it?

**Comment by alessandroperilli** [comment]
It does work fine:

<img width="1650" alt="Screenshot 2023-11-08 at 10 13 01" src="https://github.com/Trung0246/ComfyUI-0246/assets/9775949/1c1ef53c-b008-4918-8877-c538ca64c6e6">

Thank you.
