### ISSUE TITLE
Changing the input slot names, on the switch node, gives error

### ISSUE THREAD

**Issue by JorgeR81** [Trung0246/ComfyUI-0246#31]
If I change the input slot names on the switch node I get this error:

![trung](https://github.com/Trung0246/ComfyUI-0246/assets/72734038/3b0a3d8f-98b3-4404-ac29-3973e0470b14)

```
Error occurred when executing 0246.Switch:

'MiDaS Depth'

File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
res_value = old_func(*final_args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 65, in map_node_over_list
results.append(getattr(obj, func)(**input_data_all))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\nodes.py", line 2887, in execute
res.append(kwargs[kwargs[key][0]])
~~~~~~^^^^^^^^^^^^^^^^
```

**Comment by Trung0246** [comment]
Hm not intended to allows changing since the nodes rely on names to locate pins. I could see what I can do for custom names.

**Comment by JorgeR81** [comment]
I don't need to change the input slot names on the Switch node.
What I like about this, is that the names were converted to a COMBO list !

Could it be possible to display the title name of the connected nodes in the COMBO list ?
If you need the slot names, the title name could be added after the slot name, eg: **0:IMAGE Marigold Depth**.

![trung2](https://github.com/Trung0246/ComfyUI-0246/assets/72734038/fe82bd54-8b9d-40bd-ba9e-a867487500df)

![trung4](https://github.com/Trung0246/ComfyUI-0246/assets/72734038/21870eec-13ca-4977-ae8f-f0a630ba05f3)

**Comment by drmbt** [comment]
the ability to relable the names would make Hub my go to in every workflow. might it be possible to relable without actually changing the name itself?

**Comment by Trung0246** [comment]
> the ability to relable the names would make Hub my go to in every workflow. might it be possible to relable without actually changing the name itself?

I think that could possibly since that just change `label` not `name`. Label is different from name as name is the internal name that only shown when label does not exist, and label does not influence name identifier which is the main purpose of `name`.

Currently I'm a bit busy in life so not many update are happening but hopefully I'll try to fix things up for next month.

**Comment by Trung0246** [comment]
This should no longer crash with recent fixes. Hopefully everything should works now for changing input slot label directly. Changing switch slot label based on connected node is currently infeasible due to implementation issues but probably could add that in the future.

**Comment by JorgeR81** [comment]
It's working for me. Thanks.

Changing the switch labels would also be great, if possible.
The switch labels could change when we change the output labels.
