### ISSUE TITLE
Alternative DOM widget incompatible with ComfyUI's new menu beta.

### ISSUE THREAD

**Issue by Monty1836** [Trung0246/ComfyUI-0246#35]
Enabling ComfyUI's new menu beta in the settings will cause text fields to be misaligned, and move depending on your zoom level.  Disabling the Alternative DOM Widget option in the settings completely fixes the issue, at the cost of being unable to use the cloud node.
![Untitled](https://github.com/user-attachments/assets/e64e8888-47e0-47a6-9c50-8054c16b867e)

**Comment by Trung0246** [comment]
Thanks for head up. Will looks into it.

**Comment by Trung0246** [comment]
It should be fixed now.

**Comment by Monty1836** [comment]
Looks like the fix is working.  Thanks!
