### ISSUE TITLE
Making `app.showMissingNodeDialog` private starting from v1.3.17

### ISSUE THREAD

**Issue by huchenlei** [Trung0246/ComfyUI-0246#42]
See: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1210

Following code will be affected. Please remove it before v1.3.17 rolls to main repo. Thanks!
https://github.com/Trung0246/ComfyUI-0246/blob/db49a5a17d779e192321fcb38dc0b631b11bfa9e/web/js/fixes.js#L432

**Comment by Trung0246** [comment]
👍
