### ISSUE TITLE
The first input and output connections break when the workflow is loaded 

### ISSUE THREAD

**Issue by JorgeR81** [Trung0246/ComfyUI-0246#43]
I'm on Windows 10. 
I use Google Chrome and have a portable install.

When I save / load an workflow, the first input and output connections ( number 0 ) in the node break.

This also happens if I refresh the browser.

---
**Working connections:**

![t1](https://github.com/user-attachments/assets/ba5b14f3-604d-492d-a1ab-2c163f9c4a37)
---
**Broken connections:** 

![t2](https://github.com/user-attachments/assets/cf2386e4-7ba0-4679-8cd3-d4ccf6b5b41f)

---
**ComfyUI error:**

![t3](https://github.com/user-attachments/assets/f470ffca-02f9-4c0f-8e9e-9ac2c71d4ac2)

**Comment by Trung0246** [comment]
Hm is new frontend update breaks something again?

**Comment by JorgeR81** [comment]
This happens in the latest frontend: v1.3.19

And also in v1.3.11 ( which is now by default in ComfyUI ).

**Comment by Trung0246** [comment]
Guess I forgot my instance that much.

**Comment by Trung0246** [comment]
It should be fixed now.

**Comment by JorgeR81** [comment]
Yes, it's working now. Thanks !
