### ISSUE TITLE
The first port is unable to obtain a name.

### ISSUE THREAD

**Issue by cardenluo** [Trung0246/ComfyUI-0246#44]
![image](https://github.com/user-attachments/assets/e2ca0923-fa85-4e3d-bbc0-e256e5b112f9)
update latest comfyui .
Many processes are experiencing issues at the first port.

**Comment by Trung0246** [comment]
Is this occur when workflow load, new node creation, or copy-paste?

**Comment by cardenluo** [comment]
workflow load and copy-paste will occur .

**Comment by Trung0246** [comment]
Hm can't replicate this on my side. If you're download from comfy-org you could try download from comfyui-manager instead. Could make sure to update the node pack too.
