### ISSUE TITLE
[BUG] Attempting to connect a Reroute node and removing it, eliminate the _junc_in input from the Junction node

### ISSUE THREAD

**Issue by alessandroperilli** [Trung0246/ComfyUI-0246#5]
As the title says, if I attempt to connect a Reroute node to the Junction node, and then I remove it, the _junc_in input disappears and I'm forced to eliminate the node and recreate it:

<img width="293" alt="Screenshot 2023-11-07 at 13 26 29" src="https://github.com/Trung0246/ComfyUI-0246/assets/9775949/0c48e709-19cb-4976-a55b-9cf0070b38d2">

**Comment by Trung0246** [comment]
Probably same issue as https://github.com/Trung0246/ComfyUI-0246/issues/3 so I'll close this for now.
