### ISSUE TITLE
Error using Webinterface without HTTPS/TLS: crypto.subtle is undefined

### ISSUE THREAD

**Issue by zierf** [Trung0246/ComfyUI-0246#8]
Adding a Highway Node to comfy workflow prevents new images from being added to the queue if the webinterface was not opened in a secure context (HTTPS).

Reproducable using commit [#d9d8702](https://github.com/Trung0246/ComfyUI-0246/commit/b7d64ce5d90e250922a45bf7504f7628beea0ce8) (_2023-11-19_) for ComfyUI and commit [#b7d64ce](https://github.com/comfyanonymous/ComfyUI/commit/d9d8702d8dd2337c64610633f5df2dcd402379a8) (_2023-11-16_) for this extension.

---

Following error will be reported under `Settings ➜ View Logs`:
```
TypeError
can't access property "digest", crypto.subtle is undefined
randomSHA256@http://[HOSTNAME]:8188/extensions/ComfyUI-0246/js/nodes.js:41:21
```
There is no output in command line.

---

According to [MDN: SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto), the browser interface `crypto.subtle` is not usable from a website without TLS.
```
Secure context: This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.
```

So I tested this again using the webinterface behind a reverse proxy with TLS encryption, which prevented the error from being thrown.

---

For TLS support I found this related open [Issue #1105](https://github.com/comfyanonymous/ComfyUI/issues/1105) and [Pull Request #1481](https://github.com/comfyanonymous/ComfyUI/pull/1481) (not provided in aforementioned commit) in ComfyUI repository.

Even if these could solve the current problem, I don't think enabling TLS should be a requirement, especially if ComfyUI isn't exposed to the outside world. Maybe the usage of `crypto.subtle` for generating SHA-256 hashes should be replaced by a library. However, I'm not sure which one would be best for this. It's a shame that the Crypto API cannot be used for HTTP pages, even for such small use cases.

**Comment by Trung0246** [comment]
I guess I totally forgot about the `crypto.subtle` api thing only available for https. Woops. Guess I'll pick something else.

**Comment by Trung0246** [comment]
Just pushed update.
