### ISSUE TITLE
Primitive Nodes

### ISSUE THREAD

**Issue by dev-greene** [Trung0246/ComfyUI-0246#9]
I'm using a primitive node to store a string for use in multiple steps.
I can set this as the input to both my base and refiner text encodes.
I don't seem able to add this to a highway or junction though.
Am I missing something, or is this not implemented/a bug?

<img width="416" alt="image" src="https://github.com/Trung0246/ComfyUI-0246/assets/20054659/c3148dd4-b610-4985-859b-3888102c0807">

**Comment by Trung0246** [comment]
Hm primitive node is kind of impossible to use with highway or junction since they have flexible type and both Highway and Junction requires a type. You may better off to use "primitive nodes" from other extensions such as ImpactInt.
